# Generated by Django 3.0.3 on 2020-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grader',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gradeunit',
            name='grade_report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submited_file',
            field=models.FilePathField(blank=True),
        ),
    ]
