# Generated by Django 3.0.3 on 2020-02-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='identifier',
            field=models.SlugField(help_text='Will be used in course home page url', max_length=100, unique=True),
        ),
    ]
