# Generated by Django 3.0.3 on 2020-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_auto_20200206_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submited_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
