# Generated by Django 3.0.3 on 2020-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_auto_20200207_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='alert',
            field=models.TextField(blank=True, help_text='If you have any news to remind students, please enter here.'),
        ),
    ]
