# Generated by Django 3.0.3 on 2020-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_auto_20200330_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
