# Generated by Django 3.0.3 on 2020-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_auto_20200206_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submited_time',
            field=models.DateTimeField(),
        ),
    ]
