# Generated by Django 3.0.3 on 2020-03-31 03:38

from django.db import migrations, models
import oj.models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_auto_20200331_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, upload_to=oj.models.submission_file_path),
        ),
    ]
