# Generated by Django 3.0.3 on 2020-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_auto_20200206_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='total_grade',
            field=models.IntegerField(default=100),
        ),
    ]
