# Generated by Django 3.0.3 on 2020-02-06 15:04

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20200206_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, help_text='Enter a description for your assignment.'),
        ),
    ]
