# Generated by Django 3.0.3 on 2020-02-18 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a assignment name.', max_length=200)),
                ('description', mdeditor.fields.MDTextField(blank=True, help_text='Enter a description for your assignment.')),
                ('grader', models.FileField(blank=True, upload_to='')),
                ('alert', models.TextField(blank=True, help_text='如果你有什么信息想提醒学生的，请在这里输入。')),
                ('create_date', models.DateTimeField(blank=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(blank=True, help_text='Enter your student ID.', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Enter your real name.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField()),
                ('grade', models.IntegerField()),
                ('total_grade', models.IntegerField(default=100)),
                ('submited_time', models.DateTimeField()),
                ('submited_file', models.FileField(blank=True, upload_to='')),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oj.Assignment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('total_grade', models.IntegerField(default=100)),
                ('grade_report', models.TextField(blank=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oj.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(help_text='Will be used in course home page url', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Enter a course name (e.g. Math, Chinese).', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a description for your course.')),
                ('create_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oj.Course'),
        ),
    ]
