# Generated by Django 3.0.3 on 2020-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20200331_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3.14, max_digits=5),
        ),
    ]
