# Generated by Django 3.0.3 on 2020-03-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_submission_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='price',
        ),
    ]
