# Generated by Django 3.0.3 on 2020-04-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0007_remove_submission_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_grade_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
