# Generated by Django 3.0.3 on 2020-04-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0009_auto_20200401_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeunit',
            old_name='grade_report',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='gradeunit',
            old_name='submission',
            new_name='report',
        ),
    ]
